asctime == 06/26/24:12:38:20 |||------------|||
 levelname == [ERROR] |||-----------|||
 name == aiogram.event |||------------|||
 msecs - 798 -------
 Filename and funcName == (dispatcher.py).(_process_update)
 lineno == (314)
 message == Cause exception while process update id=199213293 by bot id=7487924451
TelegramBadRequest: Telegram server says - Bad Request: user not found
Traceback (most recent call last):
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 308, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 157, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\fsm\middleware.py", line 39, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 275, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 112, in trigger
    result, data = await handler.check(event, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 93, in check
    check = await event_filter.call(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\core\filters\filter.py", line 16, in __call__
    user_status = await bot.get_chat_member(str(links), message.from_user.id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\bot.py", line 1611, in get_chat_member
    return await self(call, request_timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\bot.py", line 432, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\session\base.py", line 257, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\session\aiohttp.py", line 175, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: user not found
asctime == 06/26/24:12:45:49 |||------------|||
 levelname == [ERROR] |||-----------|||
 name == aiogram.event |||------------|||
 msecs - 642 -------
 Filename and funcName == (dispatcher.py).(_process_update)
 lineno == (314)
 message == Cause exception while process update id=199213294 by bot id=7487924451
TelegramBadRequest: Telegram server says - Bad Request: user not found
Traceback (most recent call last):
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 308, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 157, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\fsm\middleware.py", line 39, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 275, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 112, in trigger
    result, data = await handler.check(event, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 93, in check
    check = await event_filter.call(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\core\filters\filter.py", line 16, in __call__
    user_status = await bot.get_chat_member(str(links), message.from_user.id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\bot.py", line 1611, in get_chat_member
    return await self(call, request_timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\bot.py", line 432, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\session\base.py", line 257, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\session\aiohttp.py", line 175, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: user not found
asctime == 06/26/24:12:46:06 |||------------|||
 levelname == [ERROR] |||-----------|||
 name == aiogram.event |||------------|||
 msecs - 597 -------
 Filename and funcName == (dispatcher.py).(_process_update)
 lineno == (314)
 message == Cause exception while process update id=199213295 by bot id=7487924451
TelegramBadRequest: Telegram server says - Bad Request: user not found
Traceback (most recent call last):
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 308, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 157, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\fsm\middleware.py", line 39, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 275, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 112, in trigger
    result, data = await handler.check(event, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 93, in check
    check = await event_filter.call(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\core\filters\filter.py", line 16, in __call__
    user_status = await bot.get_chat_member(str(links), message.from_user.id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\bot.py", line 1611, in get_chat_member
    return await self(call, request_timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\bot.py", line 432, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\session\base.py", line 257, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\session\aiohttp.py", line 175, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: user not found
asctime == 06/26/24:12:46:09 |||------------|||
 levelname == [ERROR] |||-----------|||
 name == aiogram.event |||------------|||
 msecs - 399 -------
 Filename and funcName == (dispatcher.py).(_process_update)
 lineno == (314)
 message == Cause exception while process update id=199213296 by bot id=7487924451
TelegramBadRequest: Telegram server says - Bad Request: user not found
Traceback (most recent call last):
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 308, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 157, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\fsm\middleware.py", line 39, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 275, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 112, in trigger
    result, data = await handler.check(event, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 93, in check
    check = await event_filter.call(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\core\filters\filter.py", line 16, in __call__
    user_status = await bot.get_chat_member(str(links), message.from_user.id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\bot.py", line 1611, in get_chat_member
    return await self(call, request_timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\bot.py", line 432, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\session\base.py", line 257, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\session\aiohttp.py", line 175, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: user not found
asctime == 06/26/24:12:47:13 |||------------|||
 levelname == [ERROR] |||-----------|||
 name == aiogram.event |||------------|||
 msecs - 326 -------
 Filename and funcName == (dispatcher.py).(_process_update)
 lineno == (314)
 message == Cause exception while process update id=199213297 by bot id=7487924451
TelegramBadRequest: Telegram server says - Bad Request: user not found
Traceback (most recent call last):
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 308, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 157, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\fsm\middleware.py", line 39, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 275, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 112, in trigger
    result, data = await handler.check(event, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 93, in check
    check = await event_filter.call(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\core\filters\filter.py", line 16, in __call__
    user_status = await bot.get_chat_member(str(links), message.from_user.id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\bot.py", line 1611, in get_chat_member
    return await self(call, request_timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\bot.py", line 432, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\session\base.py", line 257, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\session\aiohttp.py", line 175, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: user not found
asctime == 06/26/24:12:47:20 |||------------|||
 levelname == [ERROR] |||-----------|||
 name == aiogram.event |||------------|||
 msecs - 83 -------
 Filename and funcName == (dispatcher.py).(_process_update)
 lineno == (314)
 message == Cause exception while process update id=199213298 by bot id=7487924451
TelegramBadRequest: Telegram server says - Bad Request: user not found
Traceback (most recent call last):
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 308, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 157, in feed_update
    response = await self.update.wrap_outer_middleware(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\middlewares\error.py", line 25, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\middlewares\user_context.py", line 27, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\fsm\middleware.py", line 39, in __call__
    return await handler(event, data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 120, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\dispatcher.py", line 275, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\router.py", line 111, in _wrapped
    return await self._propagate_event(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\telegram.py", line 112, in trigger
    result, data = await handler.check(event, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 93, in check
    check = await event_filter.call(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\dispatcher\event\handler.py", line 42, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\core\filters\filter.py", line 16, in __call__
    user_status = await bot.get_chat_member(str(links), message.from_user.id)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\bot.py", line 1611, in get_chat_member
    return await self(call, request_timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\bot.py", line 432, in __call__
    return await self.session(self, method, timeout=request_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\session\base.py", line 257, in __call__
    return cast(TelegramType, await middleware(bot, method))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\session\aiohttp.py", line 175, in make_request
    response = self.check_response(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Noutbukcom\OneDrive\Ishchi stol\A\V.2.bookSearcherbot\bot\env\Lib\site-packages\aiogram\client\session\base.py", line 120, in check_response
    raise TelegramBadRequest(method=method, message=description)
aiogram.exceptions.TelegramBadRequest: Telegram server says - Bad Request: user not found
asctime == 06/26/24:12:47:30 |||------------|||
 levelname == [ERROR] |||-----------|||
 name == aiogram.dispatcher |||------------|||
 msecs - 101 -------
 Filename and funcName == (dispatcher.py).(_listen_updates)
 lineno == (218)
 message == Failed to fetch updates - TelegramNetworkError: HTTP Client says - ClientOSError: [Errno 1] [SSL: APPLICATION_DATA_AFTER_CLOSE_NOTIFY] application data after close notify (_ssl.c:2706)
asctime == 06/26/24:12:47:30 |||------------|||
 levelname == [WARNING] |||-----------|||
 name == aiogram.dispatcher |||------------|||
 msecs - 101 -------
 Filename and funcName == (dispatcher.py).(_listen_updates)
 lineno == (220)
 message == Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 7487924451)
